// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (project_id, title, content, slug, tags, status, is_public, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at, tags, views, status
`

type CreateArticleParams struct {
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	Tags      []string         `json:"tags"`
	Status    string           `json:"status"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.Tags,
		arg.Status,
		arg.IsPublic,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.Views,
		&i.Status,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getAllArticles = `-- name: GetAllArticles :many
SELECT a.id, a.project_id, p.name AS project_name, a.title, a.content, a.slug, a.tags, a.views, a.status, a.is_public, a.created_by, a.updated_by, a.created_at, a.updated_at
FROM articles a
LEFT JOIN projects p ON p.id = a.project_id
WHERE (a.is_public = true OR ($3::text IS NOT NULL AND a.created_by = $3))
  AND ($4::text IS NULL OR a.created_by = $4)
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllArticlesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
	CreatedBy        pgtype.Text `json:"created_by"`
}

type GetAllArticlesRow struct {
	ID          int64            `json:"id"`
	ProjectID   pgtype.Int8      `json:"project_id"`
	ProjectName pgtype.Text      `json:"project_name"`
	Title       string           `json:"title"`
	Content     string           `json:"content"`
	Slug        pgtype.Text      `json:"slug"`
	Tags        []string         `json:"tags"`
	Views       int64            `json:"views"`
	Status      string           `json:"status"`
	IsPublic    pgtype.Bool      `json:"is_public"`
	CreatedBy   string           `json:"created_by"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllArticles(ctx context.Context, arg GetAllArticlesParams) ([]GetAllArticlesRow, error) {
	rows, err := q.db.Query(ctx, getAllArticles,
		arg.Limit,
		arg.Offset,
		arg.RequestingUserID,
		arg.CreatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArticlesRow
	for rows.Next() {
		var i GetAllArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Title,
			&i.Content,
			&i.Slug,
			&i.Tags,
			&i.Views,
			&i.Status,
			&i.IsPublic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, project_id, title, content, slug, tags, views, status, is_public, created_by, updated_by, created_at, updated_at
FROM articles
WHERE id = $1
  AND (is_public = true OR ($2::text IS NOT NULL AND created_by = $2))
`

type GetArticleByIDParams struct {
	ID               int64       `json:"id"`
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
}

type GetArticleByIDRow struct {
	ID        int64            `json:"id"`
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	Tags      []string         `json:"tags"`
	Views     int64            `json:"views"`
	Status    string           `json:"status"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	UpdatedBy pgtype.Text      `json:"updated_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetArticleByID(ctx context.Context, arg GetArticleByIDParams) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, arg.ID, arg.RequestingUserID)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.Tags,
		&i.Views,
		&i.Status,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT a.id, a.project_id, p.name AS project_name, a.title, a.content, a.slug, a.tags, a.views, a.status, a.is_public, a.created_by, a.updated_by, a.created_at, a.updated_at
FROM articles a
LEFT JOIN projects p ON p.id = a.project_id
WHERE a.slug = $1
  AND (a.is_public = true OR ($2::text IS NOT NULL AND a.created_by = $2))
`

type GetArticleBySlugParams struct {
	Slug             pgtype.Text `json:"slug"`
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
}

type GetArticleBySlugRow struct {
	ID          int64            `json:"id"`
	ProjectID   pgtype.Int8      `json:"project_id"`
	ProjectName pgtype.Text      `json:"project_name"`
	Title       string           `json:"title"`
	Content     string           `json:"content"`
	Slug        pgtype.Text      `json:"slug"`
	Tags        []string         `json:"tags"`
	Views       int64            `json:"views"`
	Status      string           `json:"status"`
	IsPublic    pgtype.Bool      `json:"is_public"`
	CreatedBy   string           `json:"created_by"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, arg.Slug, arg.RequestingUserID)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.Tags,
		&i.Views,
		&i.Status,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticlesCount = `-- name: GetArticlesCount :one
SELECT COUNT(*) FROM articles
WHERE (is_public = true OR ($1::text IS NOT NULL AND created_by = $1))
  AND ($2::text IS NULL OR created_by = $2)
`

type GetArticlesCountParams struct {
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
	CreatedBy        pgtype.Text `json:"created_by"`
}

func (q *Queries) GetArticlesCount(ctx context.Context, arg GetArticlesCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getArticlesCount, arg.RequestingUserID, arg.CreatedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementArticleViews = `-- name: IncrementArticleViews :exec
UPDATE articles
SET views = views + 1
WHERE id = $1
`

func (q *Queries) IncrementArticleViews(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementArticleViews, id)
	return err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = COALESCE($2, title),
    content = COALESCE($3, content),
    slug = COALESCE($4, slug),
    tags = COALESCE($5, tags),
    status = COALESCE($6, status),
    is_public = COALESCE($7, is_public),
    project_id = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at, tags, views, status
`

type UpdateArticleParams struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Slug      pgtype.Text `json:"slug"`
	Tags      []string    `json:"tags"`
	Status    string      `json:"status"`
	IsPublic  pgtype.Bool `json:"is_public"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.Tags,
		arg.Status,
		arg.IsPublic,
		arg.ProjectID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.Views,
		&i.Status,
	)
	return i, err
}
