// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (project_id, title, content, slug, tags, status, is_public, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at, tags, views, status
`

type CreateArticleParams struct {
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	Tags      []string         `json:"tags"`
	Status    string           `json:"status"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.Tags,
		arg.Status,
		arg.IsPublic,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.Views,
		&i.Status,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getAllArticles = `-- name: GetAllArticles :many
SELECT id, project_id, title, content, slug, tags, views, status, is_public, created_by, updated_by, created_at, updated_at
FROM articles
WHERE ($3::text IS NULL OR created_by = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllArticlesParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	CreatedBy pgtype.Text `json:"created_by"`
}

type GetAllArticlesRow struct {
	ID        int64            `json:"id"`
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	Tags      []string         `json:"tags"`
	Views     int64            `json:"views"`
	Status    string           `json:"status"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	UpdatedBy pgtype.Text      `json:"updated_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllArticles(ctx context.Context, arg GetAllArticlesParams) ([]GetAllArticlesRow, error) {
	rows, err := q.db.Query(ctx, getAllArticles, arg.Limit, arg.Offset, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArticlesRow
	for rows.Next() {
		var i GetAllArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Slug,
			&i.Tags,
			&i.Views,
			&i.Status,
			&i.IsPublic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, project_id, title, content, slug, tags, views, status, is_public, created_by, updated_by, created_at, updated_at
FROM articles
WHERE id = $1
`

type GetArticleByIDRow struct {
	ID        int64            `json:"id"`
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	Tags      []string         `json:"tags"`
	Views     int64            `json:"views"`
	Status    string           `json:"status"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	UpdatedBy pgtype.Text      `json:"updated_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetArticleByID(ctx context.Context, id int64) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.Tags,
		&i.Views,
		&i.Status,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticlesCount = `-- name: GetArticlesCount :one
SELECT COUNT(*) FROM articles
WHERE ($1::text IS NULL OR created_by = $1)
`

func (q *Queries) GetArticlesCount(ctx context.Context, createdBy pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getArticlesCount, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementArticleViews = `-- name: IncrementArticleViews :exec
UPDATE articles
SET views = views + 1
WHERE id = $1
`

func (q *Queries) IncrementArticleViews(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementArticleViews, id)
	return err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = COALESCE($2, title),
    content = COALESCE($3, content),
    slug = COALESCE($4, slug),
    tags = COALESCE($5, tags),
    status = COALESCE($6, status),
    is_public = COALESCE($7, is_public),
    project_id = COALESCE($8, project_id),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at, tags, views, status
`

type UpdateArticleParams struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Slug      pgtype.Text `json:"slug"`
	Tags      []string    `json:"tags"`
	Status    string      `json:"status"`
	IsPublic  pgtype.Bool `json:"is_public"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.Tags,
		arg.Status,
		arg.IsPublic,
		arg.ProjectID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.Views,
		&i.Status,
	)
	return i, err
}
