// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devlog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevlog = `-- name: CreateDevlog :one
INSERT INTO devlogs (project_id, title, content, is_public, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, title, content, is_public, created_by, updated_by, created_at, updated_at
`

type CreateDevlogParams struct {
	ProjectID int64            `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateDevlog(ctx context.Context, arg CreateDevlogParams) (Devlog, error) {
	row := q.db.QueryRow(ctx, createDevlog,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.IsPublic,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Devlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevlog = `-- name: DeleteDevlog :exec
DELETE FROM devlogs
WHERE id = $1
`

func (q *Queries) DeleteDevlog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDevlog, id)
	return err
}

const getAllDevlogs = `-- name: GetAllDevlogs :many
SELECT id, project_id, title, content, is_public, created_by, updated_by, created_at, updated_at
FROM devlogs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllDevlogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllDevlogs(ctx context.Context, arg GetAllDevlogsParams) ([]Devlog, error) {
	rows, err := q.db.Query(ctx, getAllDevlogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Devlog
	for rows.Next() {
		var i Devlog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevlogByID = `-- name: GetDevlogByID :one
SELECT id, project_id, title, content, is_public, created_by, updated_by, created_at, updated_at
FROM devlogs
WHERE id = $1
`

func (q *Queries) GetDevlogByID(ctx context.Context, id int64) (Devlog, error) {
	row := q.db.QueryRow(ctx, getDevlogByID, id)
	var i Devlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevlogsByProjectID = `-- name: GetDevlogsByProjectID :many
SELECT id, project_id, title, content, is_public, created_by, updated_by, created_at, updated_at
FROM devlogs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetDevlogsByProjectIDParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetDevlogsByProjectID(ctx context.Context, arg GetDevlogsByProjectIDParams) ([]Devlog, error) {
	rows, err := q.db.Query(ctx, getDevlogsByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Devlog
	for rows.Next() {
		var i Devlog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevlogsCount = `-- name: GetDevlogsCount :one
SELECT COUNT(*) FROM devlogs
`

func (q *Queries) GetDevlogsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDevlogsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDevlogsCountByProjectID = `-- name: GetDevlogsCountByProjectID :one
SELECT COUNT(*) FROM devlogs WHERE project_id = $1
`

func (q *Queries) GetDevlogsCountByProjectID(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDevlogsCountByProjectID, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateDevlog = `-- name: UpdateDevlog :one
UPDATE devlogs
SET title = COALESCE($2, title),
    content = COALESCE($3, content),
    is_public = COALESCE($4, is_public),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, project_id, title, content, is_public, created_by, updated_by, created_at, updated_at
`

type UpdateDevlogParams struct {
	ID       int64       `json:"id"`
	Title    string      `json:"title"`
	Content  string      `json:"content"`
	IsPublic pgtype.Bool `json:"is_public"`
}

func (q *Queries) UpdateDevlog(ctx context.Context, arg UpdateDevlogParams) (Devlog, error) {
	row := q.db.QueryRow(ctx, updateDevlog,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.IsPublic,
	)
	var i Devlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
