// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int64            `json:"id"`
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	UpdatedBy pgtype.Text      `json:"updated_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Devlog struct {
	ID        int64            `json:"id"`
	ProjectID int64            `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	UpdatedBy pgtype.Text      `json:"updated_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Project struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsPublic    pgtype.Bool      `json:"is_public"`
	CreatedBy   string           `json:"created_by"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Reaction struct {
	ID           int64            `json:"id"`
	ArticleID    int64            `json:"article_id"`
	ReactionType string           `json:"reaction_type"`
	UserID       string           `json:"user_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
