// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, url, status, stack, is_public, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, is_public, created_by, updated_by, created_at, updated_at, url, status, stack
`

type CreateProjectParams struct {
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Url         pgtype.Text      `json:"url"`
	Status      string           `json:"status"`
	Stack       []string         `json:"stack"`
	IsPublic    pgtype.Bool      `json:"is_public"`
	CreatedBy   string           `json:"created_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Status,
		arg.Stack,
		arg.IsPublic,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Status,
		&i.Stack,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, name, description, url, status, stack, is_public, created_by, updated_by, created_at, updated_at
FROM projects
WHERE (is_public = true OR ($3::text IS NOT NULL AND created_by = $3))
  AND ($4::text IS NULL OR created_by = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllProjectsParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
	CreatedBy        pgtype.Text `json:"created_by"`
}

type GetAllProjectsRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Url         pgtype.Text      `json:"url"`
	Status      string           `json:"status"`
	Stack       []string         `json:"stack"`
	IsPublic    pgtype.Bool      `json:"is_public"`
	CreatedBy   string           `json:"created_by"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllProjects(ctx context.Context, arg GetAllProjectsParams) ([]GetAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, getAllProjects,
		arg.Limit,
		arg.Offset,
		arg.RequestingUserID,
		arg.CreatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsRow
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.Status,
			&i.Stack,
			&i.IsPublic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, url, status, stack, is_public, created_by, updated_by, created_at, updated_at
FROM projects
WHERE id = $1
  AND (is_public = true OR ($2::text IS NOT NULL AND created_by = $2))
`

type GetProjectByIDParams struct {
	ID               int64       `json:"id"`
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
}

type GetProjectByIDRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Url         pgtype.Text      `json:"url"`
	Status      string           `json:"status"`
	Stack       []string         `json:"stack"`
	IsPublic    pgtype.Bool      `json:"is_public"`
	CreatedBy   string           `json:"created_by"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.RequestingUserID)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Status,
		&i.Stack,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectsCount = `-- name: GetProjectsCount :one
SELECT COUNT(*) FROM projects
WHERE (is_public = true OR ($1::text IS NOT NULL AND created_by = $1))
  AND ($2::text IS NULL OR created_by = $2)
`

type GetProjectsCountParams struct {
	RequestingUserID pgtype.Text `json:"requesting_user_id"`
	CreatedBy        pgtype.Text `json:"created_by"`
}

func (q *Queries) GetProjectsCount(ctx context.Context, arg GetProjectsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectsCount, arg.RequestingUserID, arg.CreatedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    url = COALESCE($4, url),
    status = COALESCE($5, status),
    stack = COALESCE($6, stack),
    is_public = COALESCE($7, is_public),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, is_public, created_by, updated_by, created_at, updated_at, url, status, stack
`

type UpdateProjectParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Url         pgtype.Text `json:"url"`
	Status      string      `json:"status"`
	Stack       []string    `json:"stack"`
	IsPublic    pgtype.Bool `json:"is_public"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Status,
		arg.Stack,
		arg.IsPublic,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Status,
		&i.Stack,
	)
	return i, err
}
