// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getThemeSettings = `-- name: GetThemeSettings :one
SELECT id, name, bg, fg, ac, updated_by, updated_at
FROM site_settings
WHERE id = 1
`

func (q *Queries) GetThemeSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getThemeSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bg,
		&i.Fg,
		&i.Ac,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateThemeSettings = `-- name: UpdateThemeSettings :one
UPDATE site_settings
SET name = $1,
    bg = $2,
    fg = $3,
    ac = $4,
    updated_by = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, name, bg, fg, ac, updated_by, updated_at
`

type UpdateThemeSettingsParams struct {
	Name      string      `json:"name"`
	Bg        string      `json:"bg"`
	Fg        string      `json:"fg"`
	Ac        string      `json:"ac"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateThemeSettings(ctx context.Context, arg UpdateThemeSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, updateThemeSettings,
		arg.Name,
		arg.Bg,
		arg.Fg,
		arg.Ac,
		arg.UpdatedBy,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bg,
		&i.Fg,
		&i.Ac,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
