// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (project_id, title, content, slug, is_public, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at
`

type CreateArticleParams struct {
	ProjectID pgtype.Int8      `json:"project_id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Slug      pgtype.Text      `json:"slug"`
	IsPublic  pgtype.Bool      `json:"is_public"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.IsPublic,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getAllArticles = `-- name: GetAllArticles :many
SELECT id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at
FROM articles
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllArticles(ctx context.Context, arg GetAllArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, getAllArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Slug,
			&i.IsPublic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at
FROM articles
WHERE id = $1
`

func (q *Queries) GetArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticlesCount = `-- name: GetArticlesCount :one
SELECT COUNT(*) FROM articles
`

func (q *Queries) GetArticlesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getArticlesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = COALESCE($2, title),
    content = COALESCE($3, content),
    slug = COALESCE($4, slug),
    is_public = COALESCE($5, is_public),
    project_id = COALESCE($6, project_id),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, project_id, title, content, slug, is_public, created_by, updated_by, created_at, updated_at
`

type UpdateArticleParams struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Slug      pgtype.Text `json:"slug"`
	IsPublic  pgtype.Bool `json:"is_public"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.IsPublic,
		arg.ProjectID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
